# This file was generated by GoReleaser. DO NOT EDIT.
class SsmHelpers < Formula
  desc "Help manage systems with AWS Systems Manager with management helpers."
  homepage "https://github.com/disneystreaming/ssm-helpers"
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/disneystreaming/ssm-helpers/releases/download/v0.2.1/ssm-helpers_0.2.1_Darwin_x86_64.tar.gz"
    sha256 "d898dd83173797b96adfa636148b8b6f91db3006a75e6b17cfa22c51336bfe13"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/disneystreaming/ssm-helpers/releases/download/v0.2.1/ssm-helpers_0.2.1_Linux_x86_64.tar.gz"
      sha256 "d24924fecc030de717e2a8531d60fea2a3ec12cc24118ef8acebe9a8210cb19a"
    end
  end
  
  depends_on "awscli"
  depends_on "disneystreaming/tap/aws-session-manager-plugin"

  def install
    bin.install "ssm-run"
    bin.install "ssm-session"
  end
end
