# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SsmHelpers < Formula
  desc "Help manage systems with AWS Systems Manager with management helpers."
  homepage "https://github.com/disneystreaming/ssm-helpers"
  version "1.1.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/disneystreaming/ssm-helpers/releases/download/v1.1.0/ssm-helpers_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "2b4c69dd06625bad43d03d30fdfaf10e6a8a6cd20319398383a96af71a71db6a"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/disneystreaming/ssm-helpers/releases/download/v1.1.0/ssm-helpers_1.1.0_Linux_x86_64.tar.gz"
      sha256 "14d2669378556d8a6df773d62c0cee2ff9a759aa783abb77bf8fc56e237fae95"
    end
  end

  depends_on "awscli"
  depends_on "disneystreaming/tap/aws-session-manager-plugin"

  def install
    bin.install "ssm"
    bin.install_symlink  bin/"ssm" => "ssm-helpers"
  end
end
